# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Release" CACHE "STRING" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "C:/Qt_BA/6.2.4/android_x86/bin/qmake.bat" CACHE "FILEPATH" "" FORCE)
set("CMAKE_PREFIX_PATH" "C:/Qt_BA/6.2.4/android_x86" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "C:/Users/ArianneRoselinaPrana/AppData/Local/Android/Sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_COMPILER" "C:/Users/ArianneRoselinaPrana/AppData/Local/Android/Sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" CACHE "FILEPATH" "" FORCE)
set("ANDROID_NATIVE_API_LEVEL" "23" CACHE "STRING" "" FORCE)
set("ANDROID_NDK" "C:/Users/ArianneRoselinaPrana/AppData/Local/Android/Sdk/ndk/22.1.7171670" CACHE "PATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "C:/Users/ArianneRoselinaPrana/AppData/Local/Android/Sdk/ndk/22.1.7171670/build/cmake/android.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("ANDROID_USE_LEGACY_TOOLCHAIN_FILE" "OFF" CACHE "BOOL" "" FORCE)
set("ANDROID_ABI" "x86" CACHE "STRING" "" FORCE)
set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "C:/Qt_BA/6.2.4/android_x86" CACHE "PATH" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "C:/Qt_BA/6.2.4/mingw_64" CACHE "PATH" "" FORCE)
set("ANDROID_SDK_ROOT" "C:/Users/ArianneRoselinaPrana/AppData/Local/Android/Sdk" CACHE "PATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "" CACHE "STRING" "" FORCE)